name: Frontend

on:
  push:
    branches:
      - main
permissions:
  contents: write
  packages: write
  actions: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20
      - name: install pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9.12.0
      - name: login to ghcr.io
        uses: docker/login-action@v2
        with:
          username: 'mitch1009'
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: validate frontend app
        run: |
          pnpm install --no-frozen-lockfile
          pnpm frontend build
      - name: build docker image
        run: |
          pnpm docker:fr
      - name: push to ghcr.io
        run: docker push ghcr.io/mitch1009/train/train-frontend:0.0.1
  